# This is a basic workflow to help you get started with Actions

name: Compile paper

# Provide permissions to read and write the repo, create releases.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: write-all

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      # Most recent version of texlive image has broken minted/pygments
      image: ghcr.io/xu-cheng/texlive-full:20221101

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Compile paper
      run: |
        latexmk -shell-escape -pdf paper
    - name: Compile submission
      run: |
        latexmk -shell-escape -pdf submission
